### PR TITLE
New method for adding meta-data to push messages

### PR DESCRIPTION
**Pull request by Stalinko**
Pusher Beams allows passing meta data along with message parameters: https://pusher.com/docs/beams/guides/publishing-to-multiple-devices#adding-metadata-to-a-notification

I'm using that in my project and decided to format as a handy API in `PusherMessage` class.
Tests added.
Also added `.idea` folder into `.gitignore`. It's created by PHPStorm.

### CODE REVIEW

**Comment by Stalinko** [comment]
I see the style checker didn't like `!empty()` construction without space after exclamation (who writes a space after exclamation? 😱) .
If necessary I can fix. How to make it better? Make another commit and create a new PR or how?

**Comment by AndreasElia** [comment]
@Stalinko I'd probably recommend fixing the space as the entire repo follows the styleci set rules.

**Review by atymic — APPROVED** [review]
LGTM. I'll fix the style issues.

**Comment by atymic** [comment]
Could you resolve the conflicts please?

**Pull request closed without merging**
