### PR TITLE
Update related Pusher package

### PR DESCRIPTION
**Pull request by SuperDJ**
This depends on [v2.0](https://github.com/pusher/push-notifications-php/pull/42) being released

- Updated Pusher package for upcoming release https://github.com/pusher/push-notifications-php/pull/39;
- Added types;
- Added GitHub actions;
- Includes changes of other PR's:
  - [#63](https://github.com/laravel-notification-channels/pusher-push-notifications/pull/63);
  - [#64](https://github.com/laravel-notification-channels/pusher-push-notifications/pull/64);
  - [#66](https://github.com/laravel-notification-channels/pusher-push-notifications/pull/66);

### CODE REVIEW

**Comment by danharrin** [comment]
@atymic could you merge and release this please? It's blocking us from using the package

**Comment by mischasigtermans** [comment]
@themsaid @freekmurze sorry for the bump, but can this be merged please?

**Comment by mischasigtermans** [comment]
@atymic bump.

**Review by atymic — APPROVED** [review]

**Comment by atymic** [comment]
Tagged, sorry for the delay.
https://github.com/laravel-notification-channels/pusher-push-notifications/releases/tag/4.0.0

**Pull request merged**
